<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYxI6qjx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYxI6qjx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYxI6qjx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYxI6qjx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYxI6qjx\App_KernelProdContainer([
    'container.build_hash' => 'YxI6qjx',
    'container.build_id' => 'ed74209f',
    'container.build_time' => 1587368024,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYxI6qjx');
