<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin.getAll' => [[], ['_controller' => 'App\\Controller\\AdminArtworkController::index'], [], [['text', '/admin.getAll']], [], []],
    'admin.new.artwork' => [[], ['_controller' => 'App\\Controller\\AdminArtworkController::new'], [], [['text', '/Admin.new.artwork']], [], []],
    'admin.delete' => [['id'], ['_controller' => 'App\\Controller\\AdminArtworkController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/artworks']], [], []],
    'getAcrylic' => [[], ['_controller' => 'App\\Controller\\ArtworksController::getAcrylic'], [], [['text', '/getAcrylic']], [], []],
    'getPastel' => [[], ['_controller' => 'App\\Controller\\ArtworksController::getPastel'], [], [['text', '/getPastel']], [], []],
    'getInk' => [[], ['_controller' => 'App\\Controller\\ArtworksController::getInk'], [], [['text', '/getInk']], [], []],
    'getSticking' => [[], ['_controller' => 'App\\Controller\\ArtworksController::getSticking'], [], [['text', '/getSticking']], [], []],
    'getDraws' => [[], ['_controller' => 'App\\Controller\\ArtworksController::getDraws'], [], [['text', '/getDraws']], [], []],
    'getWatercolor' => [[], ['_controller' => 'App\\Controller\\ArtworksController::getWatercolor'], [], [['text', '/getWatercolor']], [], []],
    'getVarious' => [[], ['_controller' => 'App\\Controller\\ArtworksController::getVarious'], [], [['text', '/getVarious']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'contact/newMail' => [[], ['_controller' => 'App\\Controller\\ContactController::newMail'], [], [['text', '/contact/newMail']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], []],
    'news' => [[], ['_controller' => 'App\\Controller\\NewsController::index'], [], [['text', '/news']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'workshop' => [[], ['_controller' => 'App\\Controller\\WorkshopController::index'], [], [['text', '/workshop']], [], []],
    'liip_imagine_filter_runtime' => [['filter', 'hash', 'path'], ['_controller' => 'Liip\\ImagineBundle\\Controller\\ImagineController::filterRuntimeAction'], ['filter' => '[A-z0-9_-]*', 'path' => '.+'], [['variable', '/', '.+', 'path', true], ['variable', '/', '[^/]++', 'hash', true], ['text', '/rc'], ['variable', '/', '[A-z0-9_-]*', 'filter', true], ['text', '/media/cache/resolve']], [], []],
    'liip_imagine_filter' => [['filter', 'path'], ['_controller' => 'Liip\\ImagineBundle\\Controller\\ImagineController::filterAction'], ['filter' => '[A-z0-9_-]*', 'path' => '.+'], [['variable', '/', '.+', 'path', true], ['variable', '/', '[A-z0-9_-]*', 'filter', true], ['text', '/media/cache/resolve']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'logout' => [[], [], [], [['text', '/logout']], [], []],
];
