<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMgeJveU\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMgeJveU/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMgeJveU.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMgeJveU\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerMgeJveU\App_KernelTestDebugContainer([
    'container.build_hash' => 'MgeJveU',
    'container.build_id' => 'ab976178',
    'container.build_time' => 1587986997,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMgeJveU');
