<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY5tZ1Ps\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY5tZ1Ps/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY5tZ1Ps.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY5tZ1Ps\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY5tZ1Ps\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y5tZ1Ps',
    'container.build_id' => 'b39287d5',
    'container.build_time' => 1586874376,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY5tZ1Ps');
